name: macos-gcc-setup
on: [push, pull_request]
jobs:
  linux:
    name: macos-gcc-setup
    runs-on: macos-11.0
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: macos ios armv8
        run: |    
          brew install gcc@9
          cd /usr/local/bin
          ln -s gcc-9 gcc
          gcc -v
          sysctl -a | grep machdep.cpu.features
