name: macos-armv7
on: push
jobs:
  linux:
    name: macos-armv7
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: macos armv7
        run: |
          pwd
          mkdir software && cd software && mkdir gnu_getopt
          curl -o gnu-getopt.tar.gz 'https://homebrew.bintray.com/bottles/gnu-getopt-2.36.2.catalina.bottle.tar.gz'
          pwd
          echo "***check the file"
          ls
          tar -zxvf gnu-getopt.tar.gz -C ./gnu_getopt
          pwd
          echo "***done"
          brew install gnu-getopt
          echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> /Users/runner/.bash_profile
          echo 'export FLAGS_GETOPT_CMD="$(brew --prefix gnu-getopt)/bin/getopt"' >> /Users/runner/.bash_profile
          cd /Users/runner/ && . ./.bash_profile
          echo $FLAGS_GETOPT_CMD
          getopt --test
          echo $?
          cd /usr/local/opt/gnu-getopt && ls
          echo "*** check gnu-getopt done"
