name: macos-gcc-setup
on: [push, pull_request]
jobs:
  linux:
    name: macos-gcc-setup
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: macos ios armv8
        run: |
          echo "*** cat shell"
          cat /etc/shells
          brew install gcc@9
          gcc-9 -v   
          echo " " >> ~/.bash_profile
          echo "alias gcc='gcc-9'" >> ~/.bash_profile
          echo "alias cc='gcc-9'" >> ~/.bash_profile
          echo "alias g++='g++-9'" >> ~/.bash_profile
          echo "alias c++='c++-9'" >> ~/.bash_profile
          source ~/.bash_profile
          cat ~/.bash_profile
          which gcc-9
          echo "****done"
          gcc -v
