name: macos-gcc-setup
on: [push, pull_request]
jobs:
  linux:
    name: macos-gcc-setup
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: macos ios armv8
        run: |
          brew install gcc@9
          gcc-9 -v      
