name: onnx_sim test on linux
on: [push, pull_request]
jobs:
  linux:
    name: onnx_sim test on linux
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: onnx_sim test on linux 
        run: |
          pip3 install -U pip && pip3 install onnx-simplifier
          pip3 install onnx -U
          pip3 list
          mkdir onnx_models && cd onnx_models
          wget https://github.com/onnx/models/raw/master/vision/classification/squeezenet/model/squeezenet1.1-7.onnx
          echo "sim all the models"
          python3 -m onnxsim squeezenet1.1-7.onnx squeezenet1.1-7_sim.onnx
          
