name: onnx_sim test on linux
on: [push, pull_request]
jobs:
  linux:
    name: onnx_sim test on linux
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: onnx_sim test on linux 
        run: |
          pip3 install onnx-simplifier
          python3 -m onnxsim -h
          
