name: Super-Linter2

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint21:
    # Name the Job
    name: Lint code base 21
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code21
        uses: actions/checkout@v2
        
      - name: Run script21
        run: |
          echo "Begin to run the script21..."
          pwd
          ls -a
          echo "End the script21"

      # Runs the Super-Linter action
      - name: Run Super-Linter21
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
  super-lint22:
    # Name the Job
    name: Lint code base22
    # Set the type of machine to run on
    runs-on: macos-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code22
        uses: actions/checkout@v2
        
      - name: Run script22
        run: echo "Begin to run the script22..."  && pwd
          
  super-lint23:
    # Name the Job
    name: Lint code base23
    # Set the type of machine to run on
    runs-on: windows-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code23
        uses: actions/checkout@v2
        
      - name: Run script23
        run: echo "Begin to run the script23..."  && pwd
