name: windows-x64-gpu-vs2019
on: [push, pull_request]
jobs:
  windows-vs2019-gpu:
    runs-on: windows-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: cache-wget
      id: cache-wget
      uses: actions/cache@v1
      with:
        path: "wget"
        key: download-windows-wget
    - name: wget
      run: |
        mkdir software
        echo "***test wget"
        cmake -version
        mingw32-make -version
        echo "***done"
        Invoke-WebRequest -Uri http://downloads.sourceforge.net/gnuwin32/wget-1.11.4-1-bin.zip -OutFile wget.zip
        echo "***ls the path"
        ls
        echo "*** ls the path done"
        
        
        
        
        
        
        
        
        
        
